import { jsPDF } from "jspdf";
import { formatCurrency, type AnalysisResult, type Project } from "./analysis";

export function exportAnalysisToPdf(project: Project, analysis: AnalysisResult) {
  if (typeof window === "undefined") return;

  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth(); // 210mm
  const margin = 14;
  let y = 16;

  // Header Banner
  doc.setFillColor(15, 23, 42); // #0f172a
  doc.rect(margin, y, pageWidth - margin * 2, 28, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text(project.name || "Startup Assessment Report", margin + 6, y + 10);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(203, 213, 225);
  doc.text(
    `${project.industry || "General"} | ${project.business_model || "Subscription"} | Target: ${project.target_market || "Market"}`,
    margin + 6,
    y + 17
  );
  doc.text(
    `Generated by Smart Failure Detection Engine on ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
    margin + 6,
    y + 23
  );

  // Overall Risk Badge on Header
  const riskBoxX = pageWidth - margin - 45;
  doc.setFillColor(analysis.overallRisk > 50 ? 220 : 22, analysis.overallRisk > 50 ? 38 : 163, analysis.overallRisk > 50 ? 38 : 74);
  doc.roundedRect(riskBoxX, y + 6, 38, 16, 3, 3, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text("OVERALL RISK", riskBoxX + 19, y + 11, { align: "center" });
  doc.setFontSize(12);
  doc.text(`${analysis.overallRisk}%`, riskBoxX + 19, y + 18, { align: "center" });

  y += 34;

  // Key Metrics Strip
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(margin, y, pageWidth - margin * 2, 16, 2, 2, "F");
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin, y, pageWidth - margin * 2, 16, 2, 2, "D");

  const colW = (pageWidth - margin * 2) / 4;

  // Metric 1: Sector Growth
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.text("SECTOR GROWTH", margin + 6, y + 6);
  doc.setTextColor(2, 132, 199);
  doc.setFontSize(10);
  doc.text(`+${analysis.growth}%`, margin + 6, y + 12);

  // Metric 2: Overall Risk
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(7);
  doc.text("RISK INDEX", margin + colW + 6, y + 6);
  doc.setTextColor(analysis.overallRisk > 50 ? 220 : 22, analysis.overallRisk > 50 ? 38 : 163, 38);
  doc.setFontSize(10);
  doc.text(`${analysis.overallRisk}/100`, margin + colW + 6, y + 12);

  // Metric 3: ML Verdict
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(7);
  doc.text("SUCCESS CONFIDENCE", margin + colW * 2 + 6, y + 6);
  doc.setTextColor(217, 119, 6);
  doc.setFontSize(10);
  const mlConfidence = analysis.mlPrediction ? Math.round(analysis.mlPrediction.successProbability) : Math.max(5, 100 - analysis.overallRisk);
  doc.text(`${mlConfidence}%`, margin + colW * 2 + 6, y + 12);

  // Metric 4: Budget
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(7);
  doc.text("BUDGET ALLOCATED", margin + colW * 3 + 6, y + 6);
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.text(formatCurrency(project.budget || 0, project.currency || "USD"), margin + colW * 3 + 6, y + 12);

  y += 22;

  // Helper Section Heading
  function addHeading(text: string) {
    if (y > 255) {
      doc.addPage();
      y = 16;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    doc.text(text, margin, y);
    doc.setDrawColor(203, 213, 225);
    doc.line(margin, y + 2, pageWidth - margin, y + 2);
    y += 8;
  }

  // Section 1: Executive Brief
  addHeading("Executive Brief & Description");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(51, 65, 85);
  const descLines = doc.splitTextToSize(project.description || "No description provided.", pageWidth - margin * 2);
  doc.text(descLines, margin, y);
  y += descLines.length * 4.5 + 4;

  // Section 2: Risk Engine Matrix Table
  addHeading("Risk Engine Vulnerability Breakdown");

  doc.setFillColor(241, 245, 249);
  doc.rect(margin, y, pageWidth - margin * 2, 6, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(30, 41, 59);
  doc.text("CATEGORY", margin + 3, y + 4.5);
  doc.text("SCORE", margin + 40, y + 4.5);
  doc.text("SEVERITY", margin + 62, y + 4.5);
  doc.text("ANALYSIS & MITIGATION ACTION", margin + 88, y + 4.5);
  y += 7;

  (analysis.risks || []).forEach((r) => {
    const noteLines = doc.splitTextToSize(`${r.note}${r.mitigation ? ` Action: ${r.mitigation}` : ""}`, 92);
    const rowHeight = Math.max(8, noteLines.length * 3.8 + 2);

    if (y + rowHeight > 268) {
      doc.addPage();
      y = 16;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(15, 23, 42);
    doc.text(r.category, margin + 3, y + 4);

    doc.setFont("helvetica", "bold");
    doc.text(`${r.score}/100`, margin + 40, y + 4);

    const sev = r.severity || (r.score >= 70 ? "Critical" : r.score >= 45 ? "High" : "Medium");
    doc.setTextColor(r.score >= 70 ? 220 : r.score >= 45 ? 217 : 22, r.score >= 70 ? 38 : r.score >= 45 ? 119 : 163, 38);
    doc.text(sev.toUpperCase(), margin + 62, y + 4);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(51, 65, 85);
    doc.text(noteLines, margin + 88, y + 4);

    y += rowHeight;
    doc.setDrawColor(241, 245, 249);
    doc.line(margin, y - 1, pageWidth - margin, y - 1);
  });

  y += 4;

  // Section 3: Competitor Analysis Table (Fixed Overlaps)
  addHeading("Competitor Overlap & Market Matrix");

  doc.setFillColor(241, 245, 249);
  doc.rect(margin, y, pageWidth - margin * 2, 6, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(30, 41, 59);
  doc.text("COMPETITOR", margin + 3, y + 4.5);
  doc.text("OVERLAP", margin + 60, y + 4.5);
  doc.text("KEY STRENGTH", margin + 82, y + 4.5);
  doc.text("IDENTIFIED WEAKNESS", margin + 132, y + 4.5);
  y += 7;

  (analysis.competitors || []).forEach((c) => {
    // Printable Widths: Name = 53mm, Strength = 46mm, Weakness = 46mm
    const nameLines = doc.splitTextToSize(c.name, 53);
    const strLines = doc.splitTextToSize(c.strength, 46);
    const wkLines = doc.splitTextToSize(c.weakness, 46);

    const lineCount = Math.max(nameLines.length, strLines.length, wkLines.length);
    const rowHeight = Math.max(9, lineCount * 3.8 + 3);

    if (y + rowHeight > 268) {
      doc.addPage();
      y = 16;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(15, 23, 42);
    doc.text(nameLines, margin + 3, y + 4);

    doc.setFont("helvetica", "bold");
    doc.setTextColor(217, 119, 6);
    doc.text(`${c.overlap}%`, margin + 60, y + 4);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(22, 101, 52);
    doc.text(strLines, margin + 82, y + 4);

    doc.setTextColor(153, 27, 27);
    doc.text(wkLines, margin + 132, y + 4);

    y += rowHeight;
    doc.setDrawColor(241, 245, 249);
    doc.line(margin, y - 1, pageWidth - margin, y - 1);
  });

  y += 4;

  // Section 4: Feasibility Summary
  if (analysis.feasibility) {
    addHeading(`Feasibility Grade: ${analysis.feasibility.grade} (${analysis.feasibility.overallScore}%) - ${analysis.feasibility.status}`);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(51, 65, 85);
    doc.text(
      `Technical: ${analysis.feasibility.technical.score}% (${analysis.feasibility.technical.level}) | Financial: ${analysis.feasibility.financial.score}% (${analysis.feasibility.financial.level}) | Market: ${analysis.feasibility.market.score}% (${analysis.feasibility.market.level})`,
      margin,
      y
    );
    y += 8;
  }

  // Section 5: Strategic Recommendations
  addHeading("Strategic Failure Prevention Recommendations");
  (analysis.suggestions || []).forEach((s, idx) => {
    const advLines = doc.splitTextToSize(s.advice, pageWidth - margin * 2 - 4);
    const itemHeight = 4 + advLines.length * 3.5 + 4;

    if (y + itemHeight > 268) {
      doc.addPage();
      y = 16;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(15, 23, 42);
    doc.text(`${idx + 1}. ${s.title} [${s.priority.toUpperCase()}]`, margin, y);
    y += 4.5;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(51, 65, 85);
    doc.text(advLines, margin + 4, y);
    y += advLines.length * 3.5 + 3;
  });

  // Footer on all pages
  const pageCount = (doc.internal as any).getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, 283, pageWidth - margin, 283);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184);
    doc.text(`Smart Failure Detection System - Executive Risk Assessment`, margin, 288);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, 288, { align: "right" });
  }

  const filename = `${(project.name || "Startup").replace(/[^a-zA-Z0-9_\-]/g, "_")}_Executive_Risk_Report.pdf`;
  doc.save(filename);
}
